apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: workbc-sam-chefs-cron
labels:
  template: workbc-sam-chefs-cron
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
    labels: 
      app.kubernetes.io/component: api
      app.openshift.io/runtime: nodejs
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
    strategy:
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: ${NAME}${SUFFIX}
      spec:
        containers:
        - image: ${NAME}:${TAG}
          name: ${NAME}
          ports:
          - containerPort: 8000
            protocol: TCP
          resources:
            requests:
              cpu: '5m'
              memory: '20Mi'
            limits:
              cpu: '10m'
              memory: '200Mi'
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}:${TAG}
          namespace: ${IMAGE_NAMESPACE}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  spec:
    ports:
    - name: api
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: workbc-sam-chefs-cron
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: ''
- description: Tag used for the image tags
  displayName: tag
  name: TAG
  required: true
  value: latest
- description: The namespace of the OS project containing the imagestreams
  displayName: Image Namespace
  name: IMAGE_NAMESPACE
  required: true
  value: 551bf1-tools
